In [10]:
import spacy
nlp = spacy.load("en_core_web_sm")

nlp.max_length = 1198623

In [2]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text

In [41]:
d = open('ifs_report_dataset.txt', 'r', encoding='windows-1252').read()
d


'The IFRS Foundation is a not-for-profit organisationestablished to develop—in the public interest—highquality,understandable, enforceable and globally accepted accounting and sustainability disclosure standards for general purpose financial reporting, and to promote and facilitate their adoption.\nThe IFRS Foundation Trustees oversee the two boards; they, in turn, are accountable to a Monitoring Board of public authorities.\nOur mission is to develop IFRS Standards that bring transparency, accountability and efficiency to financial markets around the world.\nOur work serves the public interest by fostering trust, growth and long-term financial stability in the global economy.\nThis report covers the financial year ended 31 December 2021 and was authorised for issue in March 2022.\nWe have sought to keep this report concise, with links to further information on our website.\nIf you have questions or feedback on the report, please email communications@ifrs.org.\nTwenty years ago, the IF

In [42]:
sentences=[]
for sent in nlp(d).sents:
  sentences.append(sent)
len(sentences)

50

In [43]:
type(sentences[0].text),type(sentences[0])

(str, spacy.tokens.span.Span)

In [47]:
import string
def clean_sentence(sent):
    sent = "".join(v for v in sent if v not in string.punctuation).lower()
    sent = sent.encode("utf8").decode("ascii",'ignore')
    return sent 


In [49]:
train_data = [clean_sentence(x.text) for x in sentences]
train_data[:5]

['the ifrs foundation is a notforprofit organisationestablished to developin the public interesthighqualityunderstandable enforceable and globally accepted accounting and sustainability disclosure standards for general purpose financial reporting and to promote and facilitate their adoption\n',
 'the ifrs foundation trustees oversee the two boards they in turn are accountable to a monitoring board of public authorities\n',
 'our mission is to develop ifrs standards that bring transparency accountability and efficiency to financial markets around the world\n',
 'our work serves the public interest by fostering trust growth and longterm financial stability in the global economy\n',
 'this report covers the financial year ended 31 december 2021 and was authorised for issue in march 2022\n']

In [64]:
#tokenization:

from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

tokenizer.fit_on_texts(train_data)
total_words = len(tokenizer.word_index) + 1

In [67]:
total_words

500

In [68]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'ifrs': 4,
 'of': 5,
 'accounting': 6,
 'standards': 7,
 'in': 8,
 'for': 9,
 'a': 10,
 'on': 11,
 'our': 12,
 'financial': 13,
 'as': 14,
 'with': 15,
 'by': 16,
 'foundation': 17,
 'reporting': 18,
 'global': 19,
 'we': 20,
 'including': 21,
 'staff': 22,
 'work': 23,
 'iasb': 24,
 'new': 25,
 'requirements': 26,
 'is': 27,
 'are': 28,
 'feedback': 29,
 'an': 30,
 'technology': 31,
 'working': 32,
 'from': 33,
 'support': 34,
 'digital': 35,
 'review': 36,
 'information': 37,
 'other': 38,
 'use': 39,
 'more': 40,
 'during': 41,
 'enhanced': 42,
 'engagement': 43,
 'taxonomy': 44,
 'continue': 45,
 'public': 46,
 'sustainability': 47,
 'disclosure': 48,
 'their': 49,
 'board': 50,
 'develop': 51,
 'world': 52,
 'this': 53,
 'report': 54,
 'year': 55,
 '2021': 56,
 'further': 57,
 'it': 58,
 'its': 59,
 'system': 60,
 'provided': 61,
 'response': 62,
 'made': 63,
 'covid19': 64,
 'pandemic': 65,
 'all': 66,
 'continued': 67,
 'wellbeing': 68,
 'stakeho

In [76]:
#for every sentence we try to predict the next word (from the 1st word and appending until the sentence is over)
input_data = []
for s in train_data:
    list_tokens = tokenizer.texts_to_sequences([s])[0]
    for i in range(1, len(list_tokens)):
        actual = list_tokens[:i+1]
        input_data.append(actual)

In [81]:
input_data[:15]
#cause the first sentence is long

[[1, 4],
 [1, 4, 17],
 [1, 4, 17, 27],
 [1, 4, 17, 27, 10],
 [1, 4, 17, 27, 10, 153],
 [1, 4, 17, 27, 10, 153, 154],
 [1, 4, 17, 27, 10, 153, 154, 3],
 [1, 4, 17, 27, 10, 153, 154, 3, 155],
 [1, 4, 17, 27, 10, 153, 154, 3, 155, 1],
 [1, 4, 17, 27, 10, 153, 154, 3, 155, 1, 46],
 [1, 4, 17, 27, 10, 153, 154, 3, 155, 1, 46, 156],
 [1, 4, 17, 27, 10, 153, 154, 3, 155, 1, 46, 156, 157],
 [1, 4, 17, 27, 10, 153, 154, 3, 155, 1, 46, 156, 157, 2],
 [1, 4, 17, 27, 10, 153, 154, 3, 155, 1, 46, 156, 157, 2, 158],
 [1, 4, 17, 27, 10, 153, 154, 3, 155, 1, 46, 156, 157, 2, 158, 159]]

In [82]:
input_data.shape

AttributeError: ignored

In [84]:
tokenizer.texts_to_sequences([sentences[0].text])[0],sentences[0]
#our first sentence & it's numeric format

([1,
  4,
  17,
  27,
  10,
  9,
  154,
  3,
  1,
  46,
  157,
  2,
  158,
  159,
  6,
  2,
  47,
  48,
  7,
  9,
  160,
  161,
  13,
  18,
  2,
  3,
  162,
  2,
  87,
  49,
  163],
 The IFRS Foundation is a not-for-profit organisationestablished to develop—in the public interest—highquality,understandable, enforceable and globally accepted accounting and sustainability disclosure standards for general purpose financial reporting, and to promote and facilitate their adoption.)

In [92]:
#the length of the sentences are not equal so we need to pad: 
  #we can use the max length of the sentences but we'll use the length covered by the most (95%) of the sentences which is: 
import numpy as np
lengths=np.array([len(x) for x in input_data])
lengths

array([ 2,  3,  4, ..., 65, 66, 67])

In [97]:
max_len=round(np.percentile(lengths,95))
max_len

44

In [98]:
from keras.utils import pad_sequences
input_data = np.array(pad_sequences(input_data, maxlen=max_len, padding='pre'))
input_data.shape

(1135, 44)

In [100]:
#and here's our input data's format we need to create X and y where y will be the last value of each (4 17 27 ect)
input_data

array([[  0,   0,   0, ...,   0,   1,   4],
       [  0,   0,   0, ...,   1,   4,  17],
       [  0,   0,   0, ...,   4,  17,  27],
       ...,
       [487,   4, 488, ...,   2,   4,  47],
       [  4, 488,   2, ...,   4,  47,  48],
       [488,   2,   4, ...,  47,  48,   7]], dtype=int32)

In [122]:
X,y=input_data[:,:-1],input_data[:,-1]

In [123]:
X,y

(array([[  0,   0,   0, ...,   0,   0,   1],
        [  0,   0,   0, ...,   0,   1,   4],
        [  0,   0,   0, ...,   1,   4,  17],
        ...,
        [487,   4, 488, ...,   7,   2,   4],
        [  4, 488,   2, ...,   2,   4,  47],
        [488,   2,   4, ...,   4,  47,  48]], dtype=int32),
 array([ 4, 17, 27, ..., 47, 48,  7], dtype=int32))

In [124]:
for i in range(10):
  print(X[i])
  print("************************")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1]
************************
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 4]
************************
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  4 17]
************************
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  4 17 27]
************************
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  4 17 27 10]
************************
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   1   4  17  27  10 153]
************************
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   

In [125]:
X.shape,y.shape

((1135, 43), (1135,))

In [126]:
import tensorflow as tf

def create_model(vocabulary_size, seq_len):
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(tf.keras.layers.LSTM(150, return_sequences=True))
    model.add(tf.keras.layers.LSTM(150))
    model.add(tf.keras.layers.Dense(150, activation='relu'))

    model.add(tf.keras.layers.Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

In [127]:
model = create_model(total_words, max_len-1)


Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 43, 25)            12500     
                                                                 
 lstm_9 (LSTM)               (None, 43, 150)           105600    
                                                                 
 lstm_10 (LSTM)              (None, 150)               180600    
                                                                 
 dense_5 (Dense)             (None, 150)               22650     
                                                                 
 dense_6 (Dense)             (None, 500)               75500     
                                                                 
Total params: 396,850
Trainable params: 396,850
Non-trainable params: 0
_________________________________________________________________


In [128]:
from keras.utils import to_categorical
y = to_categorical(y, num_classes=total_words)

In [130]:
model.fit(X, y, epochs=60, verbose=1)


Epoch 1/60
36/36 [==============================] - 6s 157ms/step - loss: 1.2684 - accuracy: 0.6749
Epoch 2/60
36/36 [==============================] - 7s 200ms/step - loss: 1.2397 - accuracy: 0.6722
Epoch 3/60
36/36 [==============================] - 6s 158ms/step - loss: 1.1645 - accuracy: 0.6969
Epoch 4/60
36/36 [==============================] - 7s 199ms/step - loss: 1.1129 - accuracy: 0.7172
Epoch 5/60
36/36 [==============================] - 6s 160ms/step - loss: 1.0722 - accuracy: 0.7189
Epoch 6/60
36/36 [==============================] - 7s 199ms/step - loss: 1.0180 - accuracy: 0.7419
Epoch 7/60
36/36 [==============================] - 6s 157ms/step - loss: 0.9732 - accuracy: 0.7621
Epoch 8/60
36/36 [==============================] - 7s 201ms/step - loss: 0.9405 - accuracy: 0.7595
Epoch 9/60
36/36 [==============================] - 6s 156ms/step - loss: 0.8926 - accuracy: 0.7974
Epoch 10/60
36/36 [==============================] - 7s 200ms/step - loss: 0.8497 - accuracy: 0.8018

In [144]:
def generate_text(input_text, num_gen_words, model, max_len,tokenizer):
    for _ in range(num_gen_words):

        output_text = ""

        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        padded_encoded = pad_sequences([encoded_text], maxlen=max_len-1, padding='pre')
        predicted = model.predict(padded_encoded, verbose=0).argmax()
        
        for word,index in tokenizer.word_index.items():
            if index == predicted:
                output_text = word
                break
        input_text += " "+output_text
    return input_text.title()

In [147]:
#let's try to generate some texts
print(generate_text("The IFRS", 5, model, max_len,tokenizer))
print (generate_text("our mission is", 10, model, max_len,tokenizer))


The Ifrs Foundation Trustees Oversee The Two
Our Mission Is To Develop Ifrs Standards That Bring Transparency Accountability And Efficiency
